export const ImagePostErrors = {
	FILE_TOO_LARGE: "FILE_TOO_LARGE",
	INVALID_IMAGE_FILE: "INVALID_IMAGE_FILE",
	INVALID_IMAGE_DIMENSIONS: "INVALID_IMAGE_DIMENSIONS",
	UPLOAD_FAILED: "UPLOAD_FAILED",
	DB_INSERT_FAILED: "DB_INSERT_FAILED",
	POST_NOT_FOUND_OR_FORBIDDEN: "POST_NOT_FOUND_OR_FORBIDDEN",
	INVALID_IMAGE_URL: "INVALID_IMAGE_URL",
	COMMENT_INVALID: "COMMENT_INVALID",
	POST_NOT_FOUND: "POST_NOT_FOUND",
	COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
	COMMENT_NOT_AUTHORIZED: "COMMENT_NOT_AUTHORIZED",
} as const;

export const MessageErrors = {
	MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
	FORBIDDEN: "FORBIDDEN",
} as const;

export const AuthErrors = {
	USER_NOT_FOUND: "USER_NOT_FOUND",
	RESET_REQUEST_FAILED: "RESET_REQUEST_FAILED",
	RESET_FAILED: "RESET_FAILED",
} as const;

export const ProfileErrors = {
	USER_NOT_FOUND: "USER_NOT_FOUND",
	IMAGE_UPLOAD_FAILED: "IMAGE_UPLOAD_FAILED",
	IMAGE_PROCESSING_FAILED: "IMAGE_PROCESSING_FAILED",
	UNIQUE_CONSTRAINT_VIOLATION: "UNIQUE_CONSTRAINT_VIOLATION",
	NO_IMAGE_TO_REMOVE: "NO_IMAGE_TO_REMOVE",
	DB_UPDATE_FAILED: "DB_UPDATE_FAILED",
} as const;

export const FriendshipErrors = {
	INVALID_ACTION: "INVALID_ACTION",
} as const;

export const CommunityErrors = {
	TITLE_TOO_SHORT: "COMMUNITY_TITLE_TOO_SHORT",
	TITLE_TOO_LONG: "COMMUNITY_TITLE_TOO_LONG",
	TITLE_ALREADY_EXISTS: "COMMUNITY_TITLE_ALREADY_EXISTS",
	DESCRIPTION_TOO_LONG: "COMMUNITY_DESCRIPTION_TOO_LONG",
	NOT_FOUND: "COMMUNITY_NOT_FOUND",
	NOT_OWNER: "COMMUNITY_NOT_OWNER",
	NOT_SUBSCRIBER: "COMMUNITY_NOT_SUBSCRIBER",
	ALREADY_SUBSCRIBER: "COMMUNITY_ALREADY_SUBSCRIBER",
	ALREADY_ADMIN: "COMMUNITY_ALREADY_ADMIN",
	NOT_ADMIN: "COMMUNITY_NOT_ADMIN",
	TRANSFER_TARGET_NOT_ADMIN: "COMMUNITY_TRANSFER_TARGET_NOT_ADMIN",
	POST_NOT_FOUND: "COMMUNITY_POST_NOT_FOUND",
	POST_TITLE_TOO_SHORT: "COMMUNITY_POST_TITLE_TOO_SHORT",
	POST_TITLE_TOO_LONG: "COMMUNITY_POST_TITLE_TOO_LONG",
	POST_CONTENT_INVALID: "COMMUNITY_POST_CONTENT_INVALID",
	POST_NOT_AUTHORIZED: "COMMUNITY_POST_NOT_AUTHORIZED",
	RESPONSE_NOT_FOUND: "COMMUNITY_RESPONSE_NOT_FOUND",
	RESPONSE_CONTENT_INVALID: "COMMUNITY_RESPONSE_CONTENT_INVALID",
	RESPONSE_NOT_AUTHORIZED: "COMMUNITY_RESPONSE_NOT_AUTHORIZED",
	UPLOAD_FAILED: "COMMUNITY_UPLOAD_FAILED",
};

export const ReportErrors = {
	TARGET_NOT_FOUND: "TARGET_NOT_FOUND",
	CANNOT_REPORT_SELF: "CANNOT_REPORT_SELF",
} as const;

export const AccountDeletionErrors = {
	WRONG_PASSWORD: "WRONG_PASSWORD",
	DELETION_FAILED: "DELETION_FAILED",
} as const;
