export const ImagePostErrors = {
	FILE_TOO_LARGE: "FILE_TOO_LARGE",
	INVALID_IMAGE_FILE: "INVALID_IMAGE_FILE",
	INVALID_IMAGE_DIMENSIONS: "INVALID_IMAGE_DIMENSIONS",
	UPLOAD_FAILED: "UPLOAD_FAILED",
	DB_INSERT_FAILED: "DB_INSERT_FAILED",
	POST_NOT_FOUND_OR_FORBIDDEN: "POST_NOT_FOUND_OR_FORBIDDEN",
	INVALID_IMAGE_URL: "INVALID_IMAGE_URL",
	COMMENT_INVALID: "COMMENT_INVALID",
	POST_NOT_FOUND: "POST_NOT_FOUND",
	COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",
	COMMENT_NOT_AUTHORIZED: "COMMENT_NOT_AUTHORIZED",
} as const;

export const MessageErrors = {
	MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
	FORBIDDEN: "FORBIDDEN",
} as const;

export const AuthErrors = {
	USER_NOT_FOUND: "USER_NOT_FOUND",
	RESET_REQUEST_FAILED: "RESET_REQUEST_FAILED",
	RESET_FAILED: "RESET_FAILED",
} as const;

export const ProfileErrors = {
	USER_NOT_FOUND: "USER_NOT_FOUND",
	IMAGE_UPLOAD_FAILED: "IMAGE_UPLOAD_FAILED",
	IMAGE_PROCESSING_FAILED: "IMAGE_PROCESSING_FAILED",
	UNIQUE_CONSTRAINT_VIOLATION: "UNIQUE_CONSTRAINT_VIOLATION",
	NO_IMAGE_TO_REMOVE: "NO_IMAGE_TO_REMOVE",
	DB_UPDATE_FAILED: "DB_UPDATE_FAILED",
} as const;

export const FriendshipErrors = {
	INVALID_ACTION: "INVALID_ACTION",
} as const;
